<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ActasSeeder extends Seeder
{
    public function run(): void
    {

        $actas = [
            [
                'numero_acta' => 'ACTA-007-2025',
                'lugar_intervencion' => 'Av. Incas 123, Abancay',
                'fecha_intervencion' => Carbon::today(),
                'hora_intervencion' => '11:00:00',
                'inspector_responsable' => 'Luis_Mendoza',
                'tipo_servicio' => 'Regular',
                'tipo_agente' => 'Conductor',
                'placa' => 'GHI-789',
                'placa_vehiculo' => 'GHI-789',
                'razon_social' => 'Transporte Apurimac SAC',
                'ruc_dni' => '87654321',
                'licencia' => 'B2',
                'nombre_conductor' => 'Carlos Quispe',
                'clase_licencia' => 'B',
                'descripcion_hechos' => 'Conductor encontrado prestando servicio de transporte sin la documentación correspondiente.',
                'monto_multa' => 1200.00,
                'estado' => 1,
                'user_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'numero_acta' => 'ACTA-008-2025',
                'lugar_intervencion' => 'Av. Garzilaso 456, Abancay',
                'fecha_intervencion' => Carbon::today()->subDays(3),
                'hora_intervencion' => '08:00:00',
                'inspector_responsable' => 'Maria_Salazar',
                'tipo_servicio' => 'Especial',
                'tipo_agente' => 'Inspector',
                'placa' => 'JKL-321',
                'placa_vehiculo' => 'JKL-321',
                'razon_social' => 'Transporte Sur SAC',
                'ruc_dni' => '11223344',
                'licencia' => 'C1',
                'nombre_conductor' => 'Pedro Ramos',
                'clase_licencia' => 'C',
                'descripcion_hechos' => 'Infracción detectada durante operativo de fiscalización en servicio especial.',
                'monto_multa' => 950.00,
                'estado' => 1,
                'user_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'numero_acta' => 'ACTA-009-2025',
                'lugar_intervencion' => 'Jr. Lima 789, Abancay',
                'fecha_intervencion' => Carbon::today()->subDays(4),
                'hora_intervencion' => '13:45:00',
                'inspector_responsable' => 'Juan_Castro',
                'tipo_servicio' => 'Regular',
                'tipo_agente' => 'Conductor',
                'placa' => 'MNO-654',
                'placa_vehiculo' => 'MNO-654',
                'razon_social' => 'Transporte Andes',
                'ruc_dni' => '55667788',
                'licencia' => 'A3',
                'nombre_conductor' => 'Luis Huaman',
                'clase_licencia' => 'A',
                'descripcion_hechos' => 'Conductor operando vehículo sin cumplir con los requisitos de documentación vigente.',
                'monto_multa' => 1800.00,
                'estado' => 0,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'numero_acta' => 'ACTA-010-2025',
                'lugar_intervencion' => 'Parque Principal Abancay',
                'fecha_intervencion' => Carbon::today()->subDays(5),
                'hora_intervencion' => '17:30:00',
                'inspector_responsable' => 'Rosa_Perez',
                'tipo_servicio' => 'Especial',
                'tipo_agente' => 'Inspector',
                'placa' => 'PQR-987',
                'placa_vehiculo' => 'PQR-987',
                'razon_social' => 'Transportes Express',
                'ruc_dni' => '99887766',
                'licencia' => 'B1',
                'nombre_conductor' => 'Miguel Torees',
                'clase_licencia' => 'B',
                'descripcion_hechos' => 'Infracción por operación irregular de transporte público detectada en operativo.',
                'monto_multa' => 700.00,
                'estado' => 1,
                'user_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'numero_acta' => 'ACTA-011-2025',
                'lugar_intervencion' => 'Av. Abancay 321, Abancay',
                'fecha_intervencion' => Carbon::today()->subDays(6),
                'hora_intervencion' => '09:15:00',
                'inspector_responsable' => 'Carlos_Mendoza',
                'tipo_servicio' => 'Regular',
                'tipo_agente' => 'Conductor',
                'placa' => 'STU-159',
                'placa_vehiculo' => 'STU-159',
                'razon_social' => 'Transporte Apurimac',
                'ruc_dni' => '33445566',
                'licencia' => 'A2',
                'nombre_conductor' => 'Jorgue Salinas',
                'clase_licencia' => 'A',
                'descripcion_hechos' => 'Conductor encontrado prestando servicio con documentación incompleta.',
                'monto_multa' => 1100.00,
                'estado' => 0,
                'user_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'numero_acta' => 'ACTA-012-2025',
                'lugar_intervencion' => 'Terminar Sur Abancay',
                'fecha_intervencion' => Carbon::today()->subDays(7),
                'hora_intervencion' => '15:00:00',
                'inspector_responsable' => 'Ana_lopez',
                'tipo_servicio' => 'Especial',
                'tipo_agente' => 'Inspector',
                'placa' => 'VWX-753',
                'placa_vehiculo' => 'VWX-753',
                'razon_social' => 'Transporte Nacional',
                'ruc_dni' => '44556677',
                'licencia' => 'C2',
                'nombre_conductor' => 'Felipe Ramos',
                'clase_licencia' => 'C',
                'descripcion_hechos' => 'Vehículo operando en terminal sin autorización correspondiente.',
                'monto_multa' => 1350.00,
                'estado' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('actas')->insert($actas);
    }
}


