<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ActasSeeder extends Seeder
{
    public function run(): void
    {

        $actas = [
            [
                'numero_acta' => 'ACTA-001-2025',
                'codigo_ds' => '017-2009-MTC',
                'lugar_intervencion' => 'Av. Arenas 245, Abancay',
                'fecha_intervencion' => Carbon::today(),
                'hora_intervencion' => '08:30:00',
                'inspector_responsable' => 'Oscar_zarate',
                'tipo_servicio' => 'Regular',
                'tipo_agente' => 'Conductor',
                'placa' => 'ABC-123',
                'razon_social' => 'Transporte S.A.',
                'ruc_dni' => '12345678',
                'nombre_conductor' => 'Juan Pérez',
                'licencia' => 'A1',
                'clase_licencia' => 'A',
                'origen' => 'Abancay',
                'destino' => 'Lima',
                'numero_personas' => 20,
                'conductor_id' => 1,
                'infraccion_id' => 1,
                'descripcion_hechos' => 'Vehículo circulando sin tarjeta de operación vigente',
                'medios_probatorios' => 'N/A',
                'calificacion' => 'Grave',
                'medida_administrativa' => 'N/A',
                'sancion' => 'N/A',
                'monto_multa' => 1580.00,
                'observaciones_intervenido' => 'Conductor no pudo presentar documentos requeridos',
                'observaciones_inspector' => 'N/A',
                    'estado' => 0,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'numero_acta' => 'ACTA-002-2025',
                'codigo_ds' => '017-2009-MTC',
                'lugar_intervencion' => 'Terminal Terrestre Abancay',
                'fecha_intervencion' => Carbon::today(),
                'hora_intervencion' => '14:15:00',
                'inspector_responsable' => 'Braulio_huaman',
                'tipo_servicio' => 'Regular',
                'tipo_agente' => 'Conductor',
                'placa' => 'XYZ-789',
                'razon_social' => 'N/A',
                'ruc_dni' => 'N/A',
                'nombre_conductor' => 'N/A',
                'licencia' => 'N/A',
                'clase_licencia' => 'N/A',
                'origen' => 'N/A',
                'destino' => 'N/A',
                'numero_personas' => 0,
                'conductor_id' => 1,
                'infraccion_id' => 1,
                'descripcion_hechos' => 'Exceso de pasajeros en vehículo de transporte público',
                'medios_probatorios' => 'N/A',
                'calificacion' => 'Leve',
                'medida_administrativa' => 'N/A',
                'sancion' => 'N/A',
                'monto_multa' => 2370.00,
                'observaciones_intervenido' => 'Se detectaron 5 pasajeros adicionales al permitido',
                'observaciones_inspector' => 'N/A',
                    'estado' => 0,
                'user_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'numero_acta' => 'ACTA-003-2025',
                'codigo_ds' => '017-2009-MTC',
                'lugar_intervencion' => 'Carretera Abancay-Andahuaylas Km 15',
                'fecha_intervencion' => Carbon::today(),
                'hora_intervencion' => '10:45:00',
                'inspector_responsable' => 'Torres_Juan',
                'tipo_servicio' => 'Regular',
                'tipo_agente' => 'Conductor',
                'placa' => 'DEF-456',
                'razon_social' => 'N/A',
                'ruc_dni' => 'N/A',
                'nombre_conductor' => 'N/A',
                'licencia' => 'N/A',
                'clase_licencia' => 'N/A',
                'origen' => 'N/A',
                'destino' => 'N/A',
                'numero_personas' => 0,
                'conductor_id' => 1,
                'infraccion_id' => 1,
                'descripcion_hechos' => 'Conductor sin licencia de conducir apropiada para la categoría',
                'medios_probatorios' => 'N/A',
                'calificacion' => 'Leve',
                'medida_administrativa' => 'N/A',
                'sancion' => 'N/A',
                'monto_multa' => 3950.00,
                'observaciones_intervenido' => 'Licencia categoria A1, vehículo requiere A3',
                'observaciones_inspector' => 'N/A',
                    'estado' => 0,
                'user_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'numero_acta' => 'ACTA-004-2025',
                'codigo_ds' => '017-2009-MTC',
                'lugar_intervencion' => 'Plaza de Armas Abancay',
                'fecha_intervencion' => Carbon::yesterday(),
                'hora_intervencion' => '16:20:00',
                'inspector_responsable' => 'Jose_Ruiz',
                'tipo_servicio' => 'Regular',
                'tipo_agente' => 'Conductor',
                'placa' => 'ABC-123',
                'razon_social' => 'N/A',
                'ruc_dni' => 'N/A',
                'nombre_conductor' => 'N/A',
                'licencia' => 'N/A',
                'clase_licencia' => 'N/A',
                'origen' => 'N/A',
                'destino' => 'N/A',
                'numero_personas' => 0,
                'conductor_id' => 1,
                'infraccion_id' => 1,
                'descripcion_hechos' => 'Estacionamiento en zona prohibida',
                'medios_probatorios' => 'N/A',
                'calificacion' => 'Leve',
                'medida_administrativa' => 'N/A',
                'sancion' => 'N/A',
                'monto_multa' => 790.00,
                'observaciones_intervenido' => 'Multa pagada, expediente cerrado',
                'observaciones_inspector' => 'N/A',
                    'estado' => 1,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'numero_acta' => 'ACTA-005-2025',
                'codigo_ds' => '017-2009-MTC',
                'lugar_intervencion' => 'Mercado Central Abancay',
                'fecha_intervencion' => Carbon::yesterday(),
                'hora_intervencion' => '12:10:00',
                'inspector_responsable' => 'Joshep_Altamirano',
                'tipo_servicio' => 'Regular',
                'tipo_agente' => 'Conductor',
                'placa' => 'XYZ-789',
                'razon_social' => 'N/A',
                'ruc_dni' => 'N/A',
                'nombre_conductor' => 'N/A',
                'licencia' => 'N/A',
                'clase_licencia' => 'N/A',
                'origen' => 'N/A',
                'destino' => 'N/A',
                'numero_personas' => 0,
                'conductor_id' => 1,
                'infraccion_id' => 1,
                'descripcion_hechos' => 'Vehículo con documentos vencidos',
                'medios_probatorios' => 'N/A',
                'calificacion' => 'Leve',
                'medida_administrativa' => 'N/A',
                'sancion' => 'N/A',
                'monto_multa' => 1185.00,
                'observaciones_intervenido' => 'Documentos renovados, caso cerrado',
                'observaciones_inspector' => 'N/A',
                    'estado' => 1,
                'user_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'numero_acta' => 'ACTA-006-2025',
                'codigo_ds' => '017-2009-MTC',
                'lugar_intervencion' => 'Av. Núñez 890, Abancay',
                'fecha_intervencion' => Carbon::today()->subDays(2),
                'hora_intervencion' => '09:30:00',
                'inspector_responsable' => 'Pepe_lucho',
                'tipo_servicio' => 'Regular',
                'tipo_agente' => 'Conductor',
                'placa' => 'DEF-456',
                'razon_social' => 'N/A',
                'ruc_dni' => 'N/A',
                'nombre_conductor' => 'N/A',
                'licencia' => 'N/A',
                'clase_licencia' => 'N/A',
                'origen' => 'N/A',
                'destino' => 'N/A',
                'numero_personas' => 0,
                'conductor_id' => 1,
                'infraccion_id' => 1,
                'descripcion_hechos' => 'Vehículo en mal estado de conservación',
                'medios_probatorios' => 'N/A',
                'calificacion' => 'Leve',
                'medida_administrativa' => 'N/A',
                'sancion' => 'N/A',
                'monto_multa' => 2765.00,
                'observaciones_intervenido' => 'Pendiente de revisión técnica',
                'observaciones_inspector' => 'N/A',
                    'estado' => 0,
                'user_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('actas')->insert($actas);
    }
}


