<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConductoresSeeder extends Seeder
{
    public function run(): void
    {
        $conductores = [
            [
                'nombres' => 'Juan Carlos',
                'apellidos' => 'Pérez Gómez',
                'dni' => '12345678',
                'fecha_nacimiento' => '1985-03-15',
                'direccion' => 'Jr. Los Incas 123',
                'distrito' => 'Abancay',
                'provincia' => 'Abancay',
                'departamento' => 'Apurímac',
                'telefono' => '987654321',
                'email' => 'juan.perez@email.com',
                'numero_licencia' => 'A12345678',
                'clase_categoria' => 'A-IIb',
                'fecha_expedicion' => '2020-05-15',
                'fecha_vencimiento' => '2030-05-15',
                'estado_licencia' => 'vigente',
                'empresa_id' => 1,
                'estado' => 'activo',
                'puntos_acumulados' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'María Elena',
                'apellidos' => 'López Silva',
                'dni' => '23456789',
                'fecha_nacimiento' => '1990-07-22',
                'direccion' => 'Av. Wari 456',
                'distrito' => 'Andahuaylas',
                'provincia' => 'Andahuaylas',
                'departamento' => 'Apurímac',
                'telefono' => '976543210',
                'email' => 'maria.lopez@email.com',
                'numero_licencia' => 'A23456789',
                'clase_categoria' => 'A-IIa',
                'fecha_expedicion' => '2019-08-10',
                'fecha_vencimiento' => '2029-08-10',
                'estado_licencia' => 'vigente',
                'empresa_id' => 2,
                'estado' => 'activo',
                'puntos_acumulados' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Carlos Alberto',
                'apellidos' => 'Ruiz Mendoza',
                'dni' => '34567890',
                'fecha_nacimiento' => '1982-11-08',
                'direccion' => 'Jr. Chanka 789',
                'distrito' => 'Chincheros',
                'provincia' => 'Chincheros',
                'departamento' => 'Apurímac',
                'telefono' => '965432109',
                'email' => 'carlos.ruiz@email.com',
                'numero_licencia' => 'A34567890',
                'clase_categoria' => 'A-IIIa',
                'fecha_expedicion' => '2018-03-20',
                'fecha_vencimiento' => '2028-03-20',
                'estado_licencia' => 'vigente',
                'empresa_id' => 3,
                'estado' => 'activo',
                'puntos_acumulados' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Ana Sofía',
                'apellidos' => 'Torres Huamán',
                'dni' => '45678901',
                'fecha_nacimiento' => '1988-05-30',
                'direccion' => 'Av. Apurímac 321',
                'distrito' => 'Antabamba',
                'provincia' => 'Antabamba',
                'departamento' => 'Apurímac',
                'telefono' => '954321098',
                'email' => 'ana.torres@email.com',
                'numero_licencia' => 'A45678901',
                'clase_categoria' => 'A-IIb',
                'fecha_expedicion' => '2021-11-05',
                'fecha_vencimiento' => '2031-11-05',
                'estado_licencia' => 'vigente',
                'empresa_id' => 4,
                'estado' => 'activo',
                'puntos_acumulados' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombres' => 'Roberto Miguel',
                'apellidos' => 'Vargas Ccahuana',
                'dni' => '56789012',
                'fecha_nacimiento' => '1987-12-12',
                'direccion' => 'Jr. Inca 654',
                'distrito' => 'Grau',
                'provincia' => 'Grau',
                'departamento' => 'Apurímac',
                'telefono' => '943210987',
                'email' => 'roberto.vargas@email.com',
                'numero_licencia' => 'A56789012',
                'clase_categoria' => 'A-IIa',
                'fecha_expedicion' => '2022-06-15',
                'fecha_vencimiento' => '2032-06-15',
                'estado_licencia' => 'vigente',
                'empresa_id' => 5,
                'estado' => 'activo',
                'puntos_acumulados' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('conductores')->insert($conductores);
    }
}
