<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DatosBasicosSeeder extends Seeder
{
    public function run()
    {
        // Verificar si ya hay datos antes de insertar
        if (DB::table('vehiculos')->count() == 0) {
            // Seeder para Vehículos
            DB::table('vehiculos')->insert([
                [
                    'placa' => 'ABC-123',
                    'marca' => 'Toyota',
                    'modelo' => 'Corolla',
                    'color' => 'Blanco',
                    'año' => 2020,
                    'numero_motor' => 'TOY123456',
                    'numero_chasis' => 'CHASIS123456',
                    'clase' => 'M1',
                    'categoria' => 'Automóvil',
                    'combustible' => 'gasolina',
                    'asientos' => 5,
                    'peso_bruto' => 1500.00,
                    'carga_util' => 500.00,
                    'empresa_id' => null,
                    'conductor_id' => null,
                    'estado' => 'activo',
                    'fecha_soat' => '2025-12-31',
                    'fecha_revision_tecnica' => '2025-06-30',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'placa' => 'XYZ-789',
                    'marca' => 'Nissan',
                    'modelo' => 'Sentra',
                    'color' => 'Azul',
                    'año' => 2019,
                    'numero_motor' => 'NIS789012',
                    'numero_chasis' => 'CHASIS789012',
                    'clase' => 'M1',
                    'categoria' => 'Automóvil',
                    'combustible' => 'gasolina',
                    'asientos' => 5,
                    'peso_bruto' => 1400.00,
                    'carga_util' => 450.00,
                    'empresa_id' => null,
                    'conductor_id' => null,
                    'estado' => 'activo',
                    'fecha_soat' => '2025-08-15',
                    'fecha_revision_tecnica' => '2024-12-20',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'placa' => 'DEF-456',
                    'marca' => 'Mitsubishi',
                    'modelo' => 'L200',
                    'color' => 'Negro',
                    'año' => 2021,
                    'numero_motor' => 'MIT456789',
                    'numero_chasis' => 'CHASIS456789',
                    'clase' => 'N1',
                    'categoria' => 'Camioneta',
                    'combustible' => 'diesel',
                    'asientos' => 5,
                    'peso_bruto' => 2500.00,
                    'carga_util' => 1000.00,
                    'empresa_id' => null,
                    'conductor_id' => null,
                    'estado' => 'activo',
                    'fecha_soat' => '2026-01-15',
                    'fecha_revision_tecnica' => '2025-07-10',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ]
            ]);
        }

        if (DB::table('conductores')->count() == 0) {
            // Seeder para Conductores
            DB::table('conductores')->insert([
                [
                    'dni' => '12345678',
                    'nombres' => 'Juan Carlos',
                    'apellidos' => 'Pérez García',
                    'fecha_nacimiento' => '1985-05-15',
                    'direccion' => 'Av. Los Incas 123',
                    'distrito' => 'Abancay',
                    'provincia' => 'Abancay',
                    'departamento' => 'Apurímac',
                    'telefono' => '987654321',
                    'email' => 'juan.perez@email.com',
                    'numero_licencia' => 'L123456789',
                    'clase_categoria' => 'B-IIa',
                    'fecha_expedicion' => '2020-01-01',
                    'fecha_vencimiento' => '2025-12-31',
                    'estado_licencia' => 'vigente',
                    'empresa_id' => null,
                    'estado' => 'activo',
                    'puntos_acumulados' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'dni' => '87654321',
                    'nombres' => 'María Elena',
                    'apellidos' => 'González López',
                    'fecha_nacimiento' => '1990-08-22',
                    'direccion' => 'Jr. Huancavelica 456',
                    'distrito' => 'Abancay',
                    'provincia' => 'Abancay',
                    'departamento' => 'Apurímac',
                    'telefono' => '912345678',
                    'email' => 'maria.gonzalez@email.com',
                    'numero_licencia' => 'L987654321',
                    'clase_categoria' => 'B-I',
                    'fecha_expedicion' => '2019-07-01',
                    'fecha_vencimiento' => '2024-06-30',
                    'estado_licencia' => 'vigente',
                    'empresa_id' => null,
                    'estado' => 'activo',
                    'puntos_acumulados' => 5,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'dni' => '11223344',
                    'nombres' => 'Carlos Alberto',
                    'apellidos' => 'Rodríguez Silva',
                    'fecha_nacimiento' => '1982-12-10',
                    'direccion' => 'Av. Centenario 789',
                    'distrito' => 'Abancay',
                    'provincia' => 'Abancay',
                    'departamento' => 'Apurímac',
                    'telefono' => '998877665',
                    'email' => 'carlos.rodriguez@email.com',
                    'numero_licencia' => 'L112233445',
                    'clase_categoria' => 'B-IIc',
                    'fecha_expedicion' => '2021-03-15',
                    'fecha_vencimiento' => '2026-03-15',
                    'estado_licencia' => 'vigente',
                    'empresa_id' => null,
                    'estado' => 'activo',
                    'puntos_acumulados' => 2,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ]
            ]);
        }

        if (DB::table('inspectores')->count() == 0) {
            // Seeder para Inspectores
            DB::table('inspectores')->insert([
                [
                    'dni' => '55667788',
                    'nombres' => 'Roberto',
                    'apellidos' => 'Vargas Mendoza',
                    'codigo_inspector' => 'INS001',
                    'telefono' => '955443322',
                    'email' => 'roberto.vargas@drtcapurimac.gob.pe',
                    'fecha_ingreso' => '2018-01-15',
                    'estado' => 'activo',
                    'zona_asignada' => 'Centro Histórico',
                    'observaciones' => 'Inspector senior con experiencia en control vehicular',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'dni' => '99887766',
                    'nombres' => 'Ana Sofía',
                    'apellidos' => 'Torres Huamán',
                    'codigo_inspector' => 'INS002',
                    'telefono' => '944556677',
                    'email' => 'ana.torres@drtcapurimac.gob.pe',
                    'fecha_ingreso' => '2019-03-20',
                    'estado' => 'activo',
                    'zona_asignada' => 'Zona Norte',
                    'observaciones' => 'Especialista en inspecciones técnicas',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'dni' => '33445566',
                    'nombres' => 'Luis Miguel',
                    'apellidos' => 'Chávez Quispe',
                    'codigo_inspector' => 'INS003',
                    'telefono' => '966778899',
                    'email' => 'luis.chavez@drtcapurimac.gob.pe',
                    'fecha_ingreso' => '2020-06-10',
                    'estado' => 'activo',
                    'zona_asignada' => 'Zona Sur',
                    'observaciones' => 'Inspector especializado en documentación vehicular',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ]
            ]);
        }

        if (DB::table('infracciones')->count() == 0) {
            // Seeder para Infracciones
            DB::table('infracciones')->insert([
                [
                    'codigo_infraccion' => 'G.01',
                    'descripcion' => 'Exceso de velocidad en zona urbana',
                    'detalle_completo' => 'Conducir a velocidad superior a la máxima permitida en zona urbana (50 km/h)',
                    'gravedad' => 'muy_grave',
                    'multa_uit' => 1.20,
                    'multa_soles' => 550.00,
                    'puntos_licencia' => 8,
                    'retencion_licencia' => false,
                    'retencion_vehiculo' => false,
                    'internamiento_deposito' => false,
                    'estado' => 'activo',
                    'base_legal' => 'Art. 160 del Reglamento Nacional de Tránsito',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'codigo_infraccion' => 'L.15',
                    'descripcion' => 'Conducir sin cinturón de seguridad',
                    'detalle_completo' => 'No usar cinturón de seguridad durante la conducción',
                    'gravedad' => 'leve',
                    'multa_uit' => 0.50,
                    'multa_soles' => 230.00,
                    'puntos_licencia' => 4,
                    'retencion_licencia' => false,
                    'retencion_vehiculo' => false,
                    'internamiento_deposito' => false,
                    'estado' => 'activo',
                    'base_legal' => 'Art. 82 del Reglamento Nacional de Tránsito',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'codigo_infraccion' => 'G.05',
                    'descripcion' => 'Uso de celular mientras conduce',
                    'detalle_completo' => 'Utilizar teléfono celular o dispositivos electrónicos mientras conduce',
                    'gravedad' => 'grave',
                    'multa_uit' => 0.80,
                    'multa_soles' => 368.00,
                    'puntos_licencia' => 6,
                    'retencion_licencia' => false,
                    'retencion_vehiculo' => false,
                    'internamiento_deposito' => false,
                    'estado' => 'activo',
                    'base_legal' => 'Art. 98 del Reglamento Nacional de Tránsito',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'codigo_infraccion' => 'MG.02',
                    'descripcion' => 'No respetar semáforo en rojo',
                    'detalle_completo' => 'No detenerse ante la luz roja del semáforo',
                    'gravedad' => 'muy_grave',
                    'multa_uit' => 1.50,
                    'multa_soles' => 690.00,
                    'puntos_licencia' => 10,
                    'retencion_licencia' => true,
                    'retencion_vehiculo' => false,
                    'internamiento_deposito' => false,
                    'estado' => 'activo',
                    'base_legal' => 'Art. 45 del Reglamento Nacional de Tránsito',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'codigo_infraccion' => 'L.08',
                    'descripcion' => 'Estacionar en zona prohibida',
                    'detalle_completo' => 'Estacionar el vehículo en lugares no autorizados o prohibidos',
                    'gravedad' => 'leve',
                    'multa_uit' => 0.20,
                    'multa_soles' => 92.00,
                    'puntos_licencia' => 2,
                    'retencion_licencia' => false,
                    'retencion_vehiculo' => false,
                    'internamiento_deposito' => false,
                    'estado' => 'activo',
                    'base_legal' => 'Art. 125 del Reglamento Nacional de Tránsito',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ]
            ]);
        }
    }
}
