<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InfraccionesSeeder extends Seeder
{
    public function run(): void
    {
        $infracciones = [
            [
                'codigo_infraccion' => 'F.1',
                'aplica_sobre' => 'Sobre quien realiza la actividad de transporte sin autorización',
                'reglamento' => 'Reglamento Nacional de Administración de Transportes - RENAT',
                'norma_modificatoria' => 'D.S. N° 017-2009-MTC D.S. N° 063-2010-MTC / D.S. N° 005-2016-MTC',
                'infraccion' => 'Prestar el servicio de transporte de personas, de mercancías o mixto, sin contar con autorización otorgada por la autoridad competente o en una modalidad o ámbito diferente al autorizado',
                'clase_pago' => 'Pecuniaria',
                'sancion' => '1 UIT',
                'tipo' => 'Infracción',
                'medida_preventiva' => 'Retención de la licencia de conducir / Internamiento preventivo del vehículo',
                'gravedad' => 'Muy grave',
                'otros_responsables_otros_beneficios' => 'Responsabilidad solidaria del propietario del vehículo / Aplica el descuento de 50% (Hasta 05 días hábiles de levantada el acta de control o de notificado el Inicio del Procedimiento Administrativo Sancionador) y 30% (15 días de Notificada la Resolución de Sanción de Multa pecuniaria)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo_infraccion' => 'F.2',
                'aplica_sobre' => 'Transportista',
                'reglamento' => 'Reglamento Nacional de Administración de Transportes - RENAT',
                'norma_modificatoria' => 'D.S. N° 017-2009-MTC',
                'infraccion' => 'Permitir la utilización o utilizar, intencionalmente, los vehículos destinados a la prestación del servicio, en acciones de bloqueo, interrupción u otras que impidan el libre tránsito por las calles, carreteras, puentes, vías férreas y otras vías públicas terrestres.',
                'clase_pago' => 'No pecuniaria',
                'sancion' => 'Inhabilitación por 1 año para prestar el servicio de transporte.',
                'tipo' => 'Infracción',
                'medida_preventiva' => 'En forma sucesiva: Remoción del vehículo. Internamiento del vehículo.',
                'gravedad' => 'Muy grave',
                'otros_responsables_otros_beneficios' => 'Aplica el descuento de 50% (Hasta 05 días hábiles de levantada el acta de control o de notificado el Inicio del Procedimiento Administrativo Sancionador) y 30% (15 días de Notificada la Resolución de Sanción de Multa pecuniaria)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo_infraccion' => 'F.3',
                'aplica_sobre' => 'Conductor',
                'reglamento' => 'Reglamento Nacional de Administración de Transportes - RENAT',
                'norma_modificatoria' => 'D.S. N° 017-2009-MTC',
                'infraccion' => 'Participar como conductor de vehículos que sean utilizados en acciones de bloqueo, interrupción u otras que impidan el libre tránsito por las calles, carreteras, puentes, vías férreas y otras vías públicas terrestres',
                'clase_pago' => 'No pecuniaria',
                'sancion' => 'Suspensión 90 días de habilitación para conducir vehículos del servicio de transporte',
                'tipo' => 'Infracción',
                'medida_preventiva' => 'Al conductor: Retención de licencia de conducir.',
                'gravedad' => 'Muy grave',
                'otros_responsables_otros_beneficios' => 'Aplica el descuento de 50% (Hasta 05 días hábiles de levantada el acta de control o de notificado el Inicio del Procedimiento Administrativo Sancionador) y 30% (15 días de Notificada la Resolución de Sanción de Multa pecuniaria)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo_infraccion' => 'F.4',
                'aplica_sobre' => 'Transportista',
                'reglamento' => 'Reglamento Nacional de Administración de Transportes - RENAT',
                'norma_modificatoria' => 'D.S. N° 017-2009-MTC D.S N° 063-2010-MTC',
                'infraccion' => 'a) Negarse a entregar la información o documentación correspondiente al vehículo, a su habilitación como conductor, al servicio que presta o actividad de transporte que realiza al ser requerido para ello. b) Brindar intencionalmente información no conforme, a la autoridad competente, durante la fiscalización con el propósito de hacerla incurrir en error respecto de la autorización para prestar el servicio, de la habilitación del vehículo o la del conductor c) Incurrir en actos de simulación, suplantación u otras conductas destinadas a hacer incurrir en error a la autoridad competente respecto de la autorización para prestar el servicio, o respecto de la habilitación del vehículo o la del conductor.',
                'clase_pago' => 'No pecuniaria',
                'sancion' => 'Transportista: Suspensión 90 días de la autorización para prestar servicio en la ruta o rutas en que ocurrió la infracción, o en el servicio tratándose del transporte de mercancías o del servicio de transporte especial de personas.',
                'tipo' => 'Infracción',
                'medida_preventiva' => null,
                'gravedad' => 'Muy grave',
                'otros_responsables_otros_beneficios' => 'Aplica el descuento de 50% (Hasta 05 días hábiles de levantada el acta de control o de notificado el Inicio del Procedimiento Administrativo Sancionador) y 30% (15 días de Notificada la Resolución de Sanción de Multa pecuniaria)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo_infraccion' => 'F.5',
                'aplica_sobre' => 'Generador de carga',
                'reglamento' => 'Reglamento Nacional de Administración de Transportes - RENAT',
                'norma_modificatoria' => 'D.S. N° 017-2009-MTC D.S N° 063-2010-MTC',
                'infraccion' => 'a) Contratar el servicio de transporte con un transportista que no se encuentra autorizado, o cuya autorización es para realizar servicio de transporte privado de mercancías. b) Permitir o utilizar la vía pública como lugar habitual o constante para la carga y/o descarga de mercancías. c) Exigir que el transportista cuente con la autorización especial de la autoridad de la autoridad vial que corresponda cuando transporte bienes cuyas dimensiones o peso superen los máximos establecidos por el RNV.',
                'clase_pago' => 'Pecuniaria',
                'sancion' => '0.5 UIT',
                'tipo' => 'Infracción',
                'medida_preventiva' => null,
                'gravedad' => 'Muy grave',
                'otros_responsables_otros_beneficios' => 'Aplica el descuento de 50% (Hasta 05 días hábiles de levantada el acta de control o de notificado el Inicio del Procedimiento Administrativo Sancionador) y 30% (15 días de Notificada la Resolución de Sanción de Multa pecuniaria)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo_infraccion' => 'F.6',
                'aplica_sobre' => 'Conductor',
                'reglamento' => 'Reglamento Nacional de Administración de Transportes - RENAT',
                'norma_modificatoria' => 'D.S. N° 017-2009-MTC / D.S. N° 063-2010-MTC D.S 005-2016-MTC',
                'infraccion' => 'a) negarse a entregar la información o documentación correspondiente al vehículo, a su habilitación como conductor, al servicio que presta o actividad de transporte que realiza, al ser requerido para ello. b) brindar intencionalmente información no conforme, a la autoridad competente, durante la fiscalización con el propósito de hacerla incurrir en error respecto de la autorización para prestar el servicio, de la habilitación del vehículo o la del conductor. c) Realizar maniobras evasivas con el vehículo para evitar la fiscalización. d) Incurrir en actos de simulación, suplantación u otras conductas destinadas a hacer incurrir en error a la autoridad competente respecto de la autorización para prestar el servicio, o respecto de la habilitación del vehículo o la del conductor.',
                'clase_pago' => 'Pecuniaria',
                'sancion' => 'Suspensión de la licencia de conducir por 90 días calendario + Multa 0.5 UIT',
                'tipo' => 'Infracción',
                'medida_preventiva' => 'Retención de la licencia de conducir',
                'gravedad' => 'Muy grave',
                'otros_responsables_otros_beneficios' => 'Aplica el descuento de 50% (Hasta 05 días hábiles de levantada el acta de control o de notificado el Inicio del Procedimiento Administrativo Sancionador) y 30% (15 días de Notificada la Resolución de Sanción de Multa pecuniaria)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo_infraccion' => 'F.7',
                'aplica_sobre' => 'Conductor',
                'reglamento' => 'Reglamento Nacional de Administración de Transportes - RENAT',
                'norma_modificatoria' => 'D.S N° 005-2016-MTC',
                'infraccion' => 'Atentar contra la integridad física del inspector durante la realización de sus funciones',
                'clase_pago' => 'Pecuniaria',
                'sancion' => 'Cancelación de licencia de conducir e inhabilitación definitiva para obtener nueva licencia + Multa de 0.5 UIT',
                'tipo' => 'Infracción',
                'medida_preventiva' => 'Retención de la licencia de conducir',
                'gravedad' => 'Muy grave',
                'otros_responsables_otros_beneficios' => 'Aplica el descuento de 50% (Hasta 05 días hábiles de levantada el acta de control o de notificado el Inicio del Procedimiento Administrativo Sancionador) y 30% (15 días de Notificada la Resolución de Sanción de Multa pecuniaria)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo_infraccion' => 'F.8',
                'aplica_sobre' => 'Transportista',
                'reglamento' => 'Reglamento Nacional de Administración de Transportes - RENAT',
                'norma_modificatoria' => 'D.S N° 006-2016-MTC',
                'infraccion' => 'Prestar el servicio circulando, interrumpiendo y/o impidiendo el tránsito, en situaciones de desastre natural o emergencia, incumpliendo las disposiciones que establezca la autoridad competente para la restricción de acceso a las vías.',
                'clase_pago' => 'No pecuniaria',
                'sancion' => 'Inhabilitación por dos años del vehículo para ser utilizado en la prestación del servicio de transporte terrestre. Para el caso del conductor, se aplicará lo dispuesto en el Código M..41del Anexo I del Reglamento Nacional de Transito -Código de Transito',
                'tipo' => 'Infracción',
                'medida_preventiva' => 'Remoción del vehículo',
                'gravedad' => 'Muy grave',
                'otros_responsables_otros_beneficios' => 'Aplica el descuento de 50% (Hasta 05 días hábiles de levantada el acta de control o de notificado el Inicio del Procedimiento Administrativo Sancionador) y 30% (15 días de Notificada la Resolución de Sanción de Multa pecuniaria)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo_infraccion' => 'I.1',
                'aplica_sobre' => 'Transportista',
                'reglamento' => 'Reglamento Nacional de Administración de Transporte - RENAT',
                'norma_modificatoria' => 'D.S N° 009-2004-MTC (D) / D.S N° 017-2009-MTC',
                'infraccion' => 'No portar durante la prestación del servicio de transporte, según corresponda: a) el manifiesto de usuarios, en el transporte de personas, cuando este no sea electrónico. b) la hoja de ruta manual o electrónica, según corresponda c) en el servicio de transporte de mercancías la guía de remisión del transportista y, de ser el caso manifiesto de carga. d) el documento de habilitación del vehículo e) el certificado de Inspección Técnica Vehicular. f) el certificado del seguro obligatorio de accidente de tránsito o CAT cuando corresponda.',
                'clase_pago' => 'Pecuniaria',
                'sancion' => '0.1 UIT',
                'tipo' => 'Infracción',
                'medida_preventiva' => 'En forma sucesiva: interrupción de viaje / Retención del vehículo / internamiento del vehículo',
                'gravedad' => 'Grave',
                'otros_responsables_otros_beneficios' => 'Aplica el descuento de 50% (Hasta 05 días hábiles de levantada el acta de control o de notificado el Inicio del Procedimiento Administrativo Sancionador) y 30% (15 días de Notificada la Resolución de Sanción de Multa pecuniaria)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo_infraccion' => 'I.2',
                'aplica_sobre' => 'Conductor',
                'reglamento' => 'Reglamento Nacional de Administración de Transporte - RENAT',
                'norma_modificatoria' => 'D.S. N° 009-2004-MTC (D) / D.S. N° 017-2009-MTC',
                'infraccion' => 'a) No exhibir en cada vehículo habilitado al servicio de transporte público de personas, la modalidad del servicio, según corresponda, la razón social y el nombre comercial si lo tuviera. b) En el servicio de transporte provincial de personas, no colocar en lugar visible para el usuario, la información sobre las tarifas vigentes y la ruta autorizada.',
                'clase_pago' => 'Pecuniaria',
                'sancion' => '0.1 UIT',
                'tipo' => 'Infracción',
                'medida_preventiva' => null,
                'gravedad' => 'Grave',
                'otros_responsables_otros_beneficios' => 'Aplica el descuento de 50% (Hasta 05 días hábiles de levantada el acta de control o de notificado el Inicio del Procedimiento Administrativo Sancionador) y 30% (15 días de Notificada la Resolución de Sanción de Multa pecuniaria)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($infracciones as $infraccion) {
            DB::table('infracciones')->updateOrInsert(
                ['codigo_infraccion' => $infraccion['codigo_infraccion']], // Buscar por código único
                $infraccion // Datos a insertar/actualizar
            );
        }
    }
}
