<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InfraccionesSeeder extends Seeder
{
    public function run(): void
    {
        $infracciones = [
            [
                'codigo_infraccion' => 'G.01',
                'descripcion' => 'Exceso de velocidad en zona urbana',
                'detalle_completo' => 'Conducir a velocidad superior a la permitida en zona urbana (más de 60 km/h)',
                'gravedad' => 'grave',
                'multa_uit' => 0.84,
                'multa_soles' => 420.00,
                'puntos_licencia' => 8,
                'retencion_licencia' => false,
                'retencion_vehiculo' => false,
                'internamiento_deposito' => false,
                'estado' => 'activo',
                'base_legal' => 'Art. 318° Reglamento Nacional de Tránsito',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo_infraccion' => 'G.02',
                'descripcion' => 'No respetar señal de alto',
                'detalle_completo' => 'No detenerse completamente ante una señal de alto o semáforo en rojo',
                'gravedad' => 'grave',
                'multa_uit' => 0.84,
                'multa_soles' => 420.00,
                'puntos_licencia' => 8,
                'retencion_licencia' => false,
                'retencion_vehiculo' => false,
                'internamiento_deposito' => false,
                'estado' => 'activo',
                'base_legal' => 'Art. 281° Reglamento Nacional de Tránsito',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo_infraccion' => 'MG.01',
                'descripcion' => 'Conducir sin licencia vigente',
                'detalle_completo' => 'Conducir vehículo sin portar licencia vigente o con licencia vencida',
                'gravedad' => 'muy_grave',
                'multa_uit' => 1.68,
                'multa_soles' => 840.00,
                'puntos_licencia' => 20,
                'retencion_licencia' => true,
                'retencion_vehiculo' => true,
                'internamiento_deposito' => false,
                'estado' => 'activo',
                'base_legal' => 'Art. 288° Reglamento Nacional de Tránsito',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo_infraccion' => 'L.01',
                'descripcion' => 'Estacionar en lugar prohibido',
                'detalle_completo' => 'Estacionar vehículo en zona prohibida, frente a garajes o en espacios reservados',
                'gravedad' => 'leve',
                'multa_uit' => 0.336,
                'multa_soles' => 168.00,
                'puntos_licencia' => 4,
                'retencion_licencia' => false,
                'retencion_vehiculo' => false,
                'internamiento_deposito' => false,
                'estado' => 'activo',
                'base_legal' => 'Art. 295° Reglamento Nacional de Tránsito',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo_infraccion' => 'L.02',
                'descripcion' => 'No usar cinturón de seguridad',
                'detalle_completo' => 'Conductor o pasajeros no utilizan cinturón de seguridad durante la conducción',
                'gravedad' => 'leve',
                'multa_uit' => 0.336,
                'multa_soles' => 168.00,
                'puntos_licencia' => 4,
                'retencion_licencia' => false,
                'retencion_vehiculo' => false,
                'internamiento_deposito' => false,
                'estado' => 'activo',
                'base_legal' => 'Art. 267° Reglamento Nacional de Tránsito',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo_infraccion' => 'MG.02',
                'descripcion' => 'Conducir bajo efectos del alcohol',
                'detalle_completo' => 'Conducir vehículo con grado de alcohol superior al permitido por ley',
                'gravedad' => 'muy_grave',
                'multa_uit' => 8.4,
                'multa_soles' => 4200.00,
                'puntos_licencia' => 50,
                'retencion_licencia' => true,
                'retencion_vehiculo' => true,
                'internamiento_deposito' => true,
                'estado' => 'activo',
                'base_legal' => 'Art. 274° Reglamento Nacional de Tránsito',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo_infraccion' => 'G.03',
                'descripcion' => 'Exceso de carga en transporte público',
                'detalle_completo' => 'Transportar mayor cantidad de pasajeros o carga que la autorizada',
                'gravedad' => 'grave',
                'multa_uit' => 1.68,
                'multa_soles' => 840.00,
                'puntos_licencia' => 15,
                'retencion_licencia' => false,
                'retencion_vehiculo' => true,
                'internamiento_deposito' => false,
                'estado' => 'activo',
                'base_legal' => 'Art. 230° Reglamento Nacional de Tránsito',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo_infraccion' => 'G.04',
                'descripcion' => 'No portar SOAT vigente',
                'detalle_completo' => 'Circular sin portar el Seguro Obligatorio de Accidentes de Tránsito vigente',
                'gravedad' => 'grave',
                'multa_uit' => 0.84,
                'multa_soles' => 420.00,
                'puntos_licencia' => 8,
                'retencion_licencia' => false,
                'retencion_vehiculo' => true,
                'internamiento_deposito' => false,
                'estado' => 'activo',
                'base_legal' => 'Art. 291° Reglamento Nacional de Tránsito',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('infracciones')->insert($infracciones);
    }
}
