<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VehiculosSeeder extends Seeder
{
    public function run(): void
    {
        $vehiculos = [
            [
                'placa' => 'ABC-123',
                'marca' => 'Mercedes-Benz',
                'modelo' => 'Sprinter',
                'año' => 2019,
                'color' => 'Blanco',
                'numero_motor' => 'MB123456789',
                'numero_chasis' => 'WDB9066361S123456',
                'clase' => 'M2',
                'categoria' => 'Omnibus',
                'combustible' => 'diesel',
                'asientos' => 20,
                'peso_bruto' => 5500.00,
                'carga_util' => 2500.00,
                'empresa_id' => 1,
                'conductor_id' => null,
                'estado' => 'activo',
                'fecha_soat' => '2025-12-31',
                'fecha_revision_tecnica' => '2025-10-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'DEF-456',
                'marca' => 'Hyundai',
                'modelo' => 'County',
                'año' => 2020,
                'color' => 'Azul',
                'numero_motor' => 'HY987654321',
                'numero_chasis' => 'KMFWB81TALP654321',
                'clase' => 'M2',
                'categoria' => 'Omnibus',
                'combustible' => 'diesel',
                'asientos' => 30,
                'peso_bruto' => 7500.00,
                'carga_util' => 3000.00,
                'empresa_id' => 2,
                'conductor_id' => null,
                'estado' => 'activo',
                'fecha_soat' => '2025-11-30',
                'fecha_revision_tecnica' => '2025-09-20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'GHI-789',
                'marca' => 'Volvo',
                'modelo' => 'B7R',
                'año' => 2018,
                'color' => 'Rojo',
                'numero_motor' => 'VV456789123',
                'numero_chasis' => 'YV3R4X40JJA789123',
                'clase' => 'M3',
                'categoria' => 'Omnibus',
                'combustible' => 'diesel',
                'asientos' => 45,
                'peso_bruto' => 18000.00,
                'carga_util' => 4000.00,
                'empresa_id' => 3,
                'conductor_id' => null,
                'estado' => 'activo',
                'fecha_soat' => '2025-08-15',
                'fecha_revision_tecnica' => '2025-07-10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'JKL-012',
                'marca' => 'Isuzu',
                'modelo' => 'NPR',
                'año' => 2021,
                'color' => 'Verde',
                'numero_motor' => 'IZ789456123',
                'numero_chasis' => 'JALE5W165LA012345',
                'clase' => 'N2',
                'categoria' => 'Camion',
                'combustible' => 'diesel',
                'asientos' => 3,
                'peso_bruto' => 6500.00,
                'carga_util' => 2800.00,
                'empresa_id' => 4,
                'conductor_id' => null,
                'estado' => 'activo',
                'fecha_soat' => '2026-01-20',
                'fecha_revision_tecnica' => '2025-12-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'MNO-345',
                'marca' => 'Toyota',
                'modelo' => 'Hiace',
                'año' => 2022,
                'color' => 'Blanco',
                'numero_motor' => 'TY654321987',
                'numero_chasis' => 'JTFHZ50P8M5345678',
                'clase' => 'M1',
                'categoria' => 'Camioneta',
                'combustible' => 'gasolina',
                'asientos' => 15,
                'peso_bruto' => 3200.00,
                'carga_util' => 1500.00,
                'empresa_id' => 5,
                'conductor_id' => null,
                'estado' => 'activo',
                'fecha_soat' => '2026-03-10',
                'fecha_revision_tecnica' => '2026-01-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'placa' => 'PQR-678',
                'marca' => 'Scania',
                'modelo' => 'K410',
                'año' => 2020,
                'color' => 'Amarillo',
                'numero_motor' => 'SC321987654',
                'numero_chasis' => '9BSK4X2VXLA678901',
                'clase' => 'M3',
                'categoria' => 'Omnibus',
                'combustible' => 'diesel',
                'asientos' => 50,
                'peso_bruto' => 19000.00,
                'carga_util' => 5000.00,
                'empresa_id' => 1,
                'conductor_id' => null,
                'estado' => 'activo',
                'fecha_soat' => '2025-09-30',
                'fecha_revision_tecnica' => '2025-08-25',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('vehiculos')->insert($vehiculos);
    }
}
